name: flutter_daum_postcode
description: This package can search for addresses in Korea using Daum Postcode Service.
version: 0.0.1
homepage: https://github.com/che5ya/flutter_daum_postcode

environment:
    sdk: ">=2.13.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    json_annotation: ^4.0.1
    webview_flutter: ^2.0.10

dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: ^2.0.6
    json_serializable: ^4.1.4
